MvcRides/Models/Passenger.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MvcRides.Models
{
    public class Passenger
    {
        [Key]
        public int PassengerID { get; set; }

        public string P_FName { get; set; }

        public string P_LName { get; set; }

        public string P_Phone { get; set; }

        public string P_Email { get; set; }

        public virtual Ride Ride { get; set; }

    }
}

MvcRides/Controllers/PassengerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcRides.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.IO;

namespace MvcRides.Controllers
{
    public class PassengerController : Controller
    {
        private RideCMSContext db = new RideCMSContext();

        // GET: Passenger
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {

            return View(db.Passengers.ToList());
        }

        public ActionResult New()
        {
            //no information needed from db

            return View();
        }

        //Create new passenger
        [HttpPost]
        public ActionResult Create(string P_FName, string P_LName, string P_Phone, string P_Email)
        {

            string query = "insert into passengers (P_FName, P_LName, P_Phone, P_Email) values (@P_FName, @P_LName, @P_Phone, @P_Email)";
            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@P_FName", P_FName);
            myparams[1] = new SqlParameter("@P_LName", P_LName);
            myparams[2] = new SqlParameter("@P_Phone", P_Phone);
            myparams[3] = new SqlParameter("@P_Email", P_Email);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        // GET: Passenger/Edit/5
        public ActionResult Edit(int? id)
        {
            Debug.WriteLine("testing passenger edit");
            if ((id == null) || (db.Passengers.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from passengers where PassengerID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            Passenger mypassenger = db.Passengers.SqlQuery(query, param).FirstOrDefault();
            return View(mypassenger);
        }
        // POST: passengers/Edit/5

        [HttpPost]

        public ActionResult Edit(int id, string P_FName, string P_LName, string P_Phone, string P_Email)
        {

            if ((id == null) || (db.Passengers.Find(id)) == null)
            {
                return HttpNotFound();
            }

            string query = "update passengers set P_FName=@P_FName, P_LName=@P_LName, P_Phone = @P_Phone, P_Email = @P_Email where PassengerID = @id";
            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@id", id);
            myparams[1] = new SqlParameter("@P_FName", P_FName);
            myparams[2] = new SqlParameter("@P_LName", P_LName);
            myparams[3] = new SqlParameter("@P_Phone", P_Phone);
            myparams[4] = new SqlParameter("@P_Email", P_Email);


            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        //delete Passenger
        // GET: Passengers/Delete


        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Passengers.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "delete from passengers where PassengerID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");

        }
    }
}

MvcRides/Views/Passenger/Create.cshtml
@model MvcRides.Models.Passenger

@{
    ViewBag.Title = "Create";
}

<h2>Create Passenger</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Passenger</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.P_FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.P_Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.P_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.P_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.P_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcRides/Views/Passenger/Delete.cshtml
@model MvcRides.Models.Passenger
@{
    ViewBag.Title = "Delete";
}



<h2>Delete</h2>
<h3> Are you sure?</h3>
<h4> Passenger </h4>
<hr />
<d1 class="d1-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.P_FName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.P_FName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.P_LName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.P_LName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.P_Phone)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.P_Phone)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.P_Email)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.P_Email)
    </dd>


</d1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")

    </div>
}

MvcRides/Views/Passenger/Edit.cshtml
@model MvcRides.Models.Passenger
@{
    ViewBag.Title = "Edit";
}





<h2>Edit</h2>

<form method="POST" action="/Passenger/Edit/@Model.PassengerID">
    <div>
        <label>First Name</label>
        <input type="text" value="@Model.P_FName" name="P_FName" />
    </div>
    <div>
        <label>Last Name</label>
        <input type="text" value="@Model.P_LName" name="P_LName" />
    </div>
    <div>
        <label>Phone</label>
        <input type="text" value="@Model.P_Phone" name="P_Phone" />
    </div>
    <div>
        <label>Email</label>
        <input type="text" value="@Model.P_Email" name="P_Email" />
    </div>


    <div>
        <input type="submit" value="Submit" />
    </div>
</form>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcRides/Views/Passenger/List.cshtml
@model IEnumerable<MvcRides.Models.Passenger>
@{
    ViewBag.Title = "List";
}


<div class="banner" id="passengerbanner">
</div>
<h2>List of passengers</h2>
<div class="recadd">
    @Html.ActionLink("New Passenger", "New", "Passenger")
</div>



<table id="TableHeader" class="table">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Phone</th>
        <th>Email</th>


    </tr>
    @foreach (var item in Model)


    {
        <tr>

            <td>@item.P_FName</td>
            <td>@item.P_LName</td>
            <td>@item.P_Phone</td>
            <td>@item.P_Email</td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PassengerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.PassengerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PassengerID })
            </td>
        </tr>
    }
</table>







<div style="overflow:hidden;margin-top:10px;">
    @foreach (var passenger in Model)
    {

        <div>
            @Html.ActionLink(passenger.P_FName, "Edit/" + passenger.PassengerID, "Passenger")
        </div>


    }
</div>

MvcRides/Views/Passenger/New.cshtml
@model MvcRides.Models.Passenger
@{
    ViewBag.Title = "List";
}


<div class="banner" id="passengerbanner">
</div>
<h2>New  Passenger</h2>

<form id="myform" action="/Passenger/Create" method="POST">
    <div class="inputrow">
        <label class="inputlabel"> First Name</label>
        <input type="text" name="P_FName" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Last Name</label>
        <input type="text" name="P_LName" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Phone Number </label>
        <input type="text" name="P_Phone" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Email </label>
        <input type="text" name="P_Email" />
    </div>
    <div class="inputrow">
        <input type="submit" value="add passenger" />
    </div>
</form>

<br />

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}