MvcRides/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace MvcRides.Models
{
    public class Driver
    {
        [Key]
        public int DriverID { get; set; }


        public string D_FName { get; set; }


        public string D_LName { get; set; }


        public string D_Age { get; set; }

        
        public string D_Email { get; set; }


        public string D_Phone { get; set; }


        //public string Drivers { get; set; }

        public virtual ICollection<Passenger> Passengers { get; set; }
        

       





    }

}

MvcRides/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcRides.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.IO;


namespace MvcRides.Controllers
{
    public class DriverController : Controller

    {
        private RideCMSContext db = new RideCMSContext();
        // GET: Driver
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {

            return View(db.Drivers.ToList());
        }

        public ActionResult New()
        {
            //no information needed from db

            return View();
        }
        // Create new driver
        [HttpPost]
        public ActionResult Create(string D_FName, string D_LName, string D_Age, string D_Email, string D_Phone)
        {
            //actually ask to put info into db

            string query = "insert into drivers (D_FName, D_LName, D_Age, D_Email, D_Phone) values (@D_FName, @D_LName, @D_Age, @D_Email, @D_Phone)";
            SqlParameter[] myparams = new SqlParameter[5];
            myparams[0] = new SqlParameter("@D_FName", D_FName);
            myparams[1] = new SqlParameter("@D_LName", D_LName);
            myparams[2] = new SqlParameter("@D_Age", D_Age);
            myparams[3] = new SqlParameter("@D_Email", D_Email);
            myparams[4] = new SqlParameter("@D_Phone", D_Phone);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        // GET: Driver/Edit/5
        public ActionResult Edit(int? id)
        {
            Debug.WriteLine("testing driver edit");
            if ((id == null) || (db.Drivers.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from drivers where DriverID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            Driver mydriver = db.Drivers.SqlQuery(query, param).FirstOrDefault();
            return View(mydriver);
        }
        // POST: drivers/Edit/5

        [HttpPost]

        public ActionResult Edit(int id, string D_FName, string D_LName, string D_Age, string D_Email, string D_Phone)
        {

            if ((id == null) || (db.Drivers.Find(id)) == null)
            {
                return HttpNotFound();
            }

            string query = "update drivers set D_FName=@D_FName, D_LName=@D_LName, D_Age = @D_Age, D_Email = @D_Email, D_Phone=@D_Phone where DriverID = @id";
            SqlParameter[] myparams = new SqlParameter[6];
            myparams[0] = new SqlParameter("@id", id);
            myparams[1] = new SqlParameter("@D_FName", D_FName);
            myparams[2] = new SqlParameter("@D_LName", D_LName);
            myparams[3] = new SqlParameter("@D_Age", D_Age);
            myparams[4] = new SqlParameter("@D_Email", D_Email);
            myparams[5] = new SqlParameter("@D_Phone", D_Phone);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        //delete driver
        // GET: Drivers/Delete


        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Drivers.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "delete from Drivers where DriverID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");

        }
    }
}

MvcRides/Views/Driver/Delete.cshtml
@model MvcRides.Models.Driver
@{
    ViewBag.Title = "Delete";
}



<h2>Delete</h2>
<h3> Are you sure?</h3>
<h4> Driver </h4>
<hr />
<d1 class="d1-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.D_FName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.D_FName)
    </dd>
    <dt>
    @Html.DisplayNameFor(model => model.D_LName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.D_LName)
    </dd>
    <dt>
    @Html.DisplayNameFor(model => model.D_Age)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.D_Age)
    </dd>
    <dt>
    @Html.DisplayNameFor(model => model.D_Email)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.D_Email)
    </dd>
    <dt>
    @Html.DisplayNameFor(model => model.D_Phone)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.D_Phone)
    </dd>

</d1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")

    </div>
}

MvcRides/Views/Driver/Edit.cshtml
@model MvcRides.Models.Driver
@{
    ViewBag.Title = "Edit";
}



<h2>Edit Driver</h2>

<form method="POST" action="/Driver/Edit/@Model.DriverID">
    <div>
        <label>First Name</label>
        <input type="text" value="@Model.D_FName" name="D_FName" />
    </div>
    <div>
        <label>Last Name</label>
        <input type="text" value="@Model.D_LName" name="D_LName" />
    </div>
    <div>
        <label>Age</label>
        <input type="text" value="@Model.D_Age" name="D_Age" />
    </div>
    <div>
        <label>Email</label>
        <input type="text" value="@Model.D_Email" name="D_Email" />
    </div>
    <div>
        <label>Phone</label>
        <input type="text" value="@Model.D_Phone" name="D_Phone" />
    </div>

    <div>
        <input type="submit" value="Submit" />
    </div>
</form>



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcRides/Views/Driver/List.cshtml
@model IEnumerable<MvcRides.Models.Driver>
@{
    ViewBag.Title = "List";
}


<div class="banner" id="driverbanner">

</div>
<h2>List of Drivers</h2>


<div class="recadd">
    @Html.ActionLink("New Driver", "New", "Driver")
</div>

<table id="TableHeader" class="table">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Email</th>
        <th>Phone</th>

    </tr>
    @foreach (var item in Model)

    {
        <tr>

            <td>@item.D_FName</td>
            <td>@item.D_LName</td>
            <td>@item.D_Age</td>
            <td>@item.D_Email</td>
            <td>@item.D_Phone</td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DriverID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DriverID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DriverID })
            </td>
        </tr>
    }
</table>

MvcRides/Views/Driver/New.cshtml
@model MvcRides.Models.Driver
@{
               
                ViewBag.Title = "New";
}

<h2>New Driver</h2>

<form id="myform" action="/Driver/Create" method="POST">
    <div class="inputrow">
        <label class="inputlabel"> First Name</label>
        <input type="text" name="D_FName" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Last Name</label>
        <input type="text" name="D_LName" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Age </label>
        <input type="text" name="D_Age" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Email </label>
        <input type="text" name="D_Email" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Phone Number </label>
        <input type="text" name="D_Phone" />
    </div>

    <div class="inputrow">
        <input type="submit" value="Submit" />
    </div>
</form>

<br />

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}