MvcRides/Models/Ride.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;


namespace MvcRides.Models
{
    public class Ride
    {
        [Key]
        public int RideID { get; set; }

        public string departureCity { get; set; }

        public string arrivalCity { get; set; }

        public string pickSpot { get; set; }

        public string dropSpot { get; set; }

        public string distance { get; set; }

        public String departureDate { get; set; }

        public String departureTime { get; set; }

        public int price { get; set; }

        public virtual ICollection<Passenger> passengers { get; set; }
    }
}

MvcRides/Controllers/RideController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcRides.Models;
using System.Diagnostics;
using System.Data.SqlClient;
using System.IO;

namespace MvcRides.Controllers
{
    public class RideController : Controller
    {
        private RideCMSContext db = new RideCMSContext();
        // GET: Ride
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {

            return View(db.Rides.ToList());
        }

        public ActionResult New()
        {
            //no information needed from db

            return View();
        }
        //create new Ride
        [HttpPost]

        public ActionResult Create(string departureCity, string arrivalCity, string pickSpot, string dropSpot, string distance, string departureDate, string departureTime, int price)
        {
            //actually ask to put info into db

            string query = "insert into Rides (departureCity, arrivalCity, pickSpot, dropSpot, distance, departureDate, departureTime, price) values (@departureCity, @arrivalCity, @pickSpot, @dropSpot, @distance, @departureDate, @departureTime, @price)";
            SqlParameter[] myparams = new SqlParameter[8];
            myparams[0] = new SqlParameter("@departureCity", departureCity);
            myparams[1] = new SqlParameter("@arrivalCity", arrivalCity);
            myparams[2] = new SqlParameter("@pickSpot", pickSpot);
            myparams[3] = new SqlParameter("@dropSpot", dropSpot);
            myparams[4] = new SqlParameter("@distance", distance);
            myparams[5] = new SqlParameter("@departureDate", departureDate);
            myparams[6] = new SqlParameter("@departureTime", departureTime);
            myparams[7] = new SqlParameter("@price", price);


            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        // GET: ride/Edit/5
        public ActionResult Edit(int? id)
        {

            if ((id == null) || (db.Rides.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from rides where RideID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            Ride myride = db.Rides.SqlQuery(query, param).FirstOrDefault();
            return View(myride);
        }
        // POST: ride/Edit/5

        [HttpPost]

        public ActionResult Edit(int id, string departureCity, string arrivalCity, string pickSpot, string dropSpot, string distance, string departureDate, string departureTime, int price)
        {

            if ((id == null) || (db.Rides.Find(id)) == null)
            {
                return HttpNotFound();
            }

            string query = "update rides set departureCity=@departureCity, arrivalCity=@arrivalCity, pickSpot = @pickSpot, dropSpot=@dropSpot, distance=@distance, departureDate=@departureDate, departureTime = @departureTime, price=@price  where RideID = @id";
            SqlParameter[] myparams = new SqlParameter[9];
            myparams[0] = new SqlParameter("@id", id);
            myparams[1] = new SqlParameter("@departureCity", departureCity);
            myparams[2] = new SqlParameter("@arrivalCity", arrivalCity);
            myparams[3] = new SqlParameter("@pickSpot", pickSpot);
            myparams[4] = new SqlParameter("@dropSpot", dropSpot);
            myparams[5] = new SqlParameter("@distance", distance);
            myparams[6] = new SqlParameter("@departureDate", departureDate);
            myparams[7] = new SqlParameter("@departureTime", departureTime);
            myparams[8] = new SqlParameter("@price", price);


            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }
        //delete Ride
        // GET: Rides/Delete


        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Rides.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "delete from rides where RideID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");

        }
    }
}

MvcRides/Views/Ride/Delete.cshtml
@model MvcRides.Models.Ride
@{
    ViewBag.Title = "Delete";
}



<h2>Delete</h2>
<h3> Are you sure?</h3>
<h4> Passenger </h4>
<hr />
<d1 class="d1-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.departureCity)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.departureCity)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.arrivalCity)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.arrivalCity)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.pickSpot)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.pickSpot)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.dropSpot)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.dropSpot)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.distance)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.distance)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.departureDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.departureDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.departureTime)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.departureTime)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.price)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.price)
    </dd>


</d1>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")

    </div>
}

MvcRides/Views/Ride/Edit.cshtml
@model MvcRides.Models.Ride
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form method="POST" action="/Ride/Edit/@Model.RideID">
    <div>
        <label>Departure City</label>
        <input type="text" value="@Model.departureCity" name="departureCity" />
    </div>
    <div>
        <label>Arrival City</label>
        <input type="text" value="@Model.arrivalCity" name="arrivalCity" />
    </div>
    <div>
        <label>Pick Spot</label>
        <input type="text" value="@Model.pickSpot" name="pickSpot" />
    </div>
    <div>
        <label>Drop Spot</label>
        <input type="text" value="@Model.dropSpot" name="dropSpot" />
    </div>
    <div>
        <label>Distance</label>
        <input type="text" value="@Model.distance" name="distance" />
    </div>
    <div>
        <label>Departure Date</label>
        <input type="text" value="@Model.departureDate" name="departureDate" />
    </div>
    <div>
        <label>Departure Time</label>
        <input type="text" value="@Model.departureTime" name="departureTime" />
    </div>
    <div>
        <label>price</label>
        <input type="text" value="@Model.price" name="price" />
    </div>

    <div>
        <input type="submit" value="Submit" />
    </div>
</form>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcRides/Views/Ride/List.cshtml
@model IEnumerable<MvcRides.Models.Ride>
@{
                

                ViewBag.Title = "List";
}


<div class="banner" id="ridebanner">

</div>

<h2>List of Rides</h2>


<div class="recadd">
    @Html.ActionLink("New Ride", "New", "Ride")
</div>

<table id="TableHeader" class="table">

    <tr>
        <th>From</th>
        <th>To </th>
        <th>Pick Spot</th>
        <th>Drop Spot</th>
        <th>Distance</th>
        <th>Departure Date</th>
        <th>Departure Time</th>
        <th>Price</th>

    </tr>
    @foreach (var item in Model)

    {
        <tr>

            <td>@item.departureCity</td>
            <td>@item.arrivalCity</td>
            <td>@item.pickSpot</td>
            <td>@item.dropSpot</td>
            <td>@item.distance</td>
            <td>@item.departureDate</td>
            <td>@item.departureTime</td>
            <td>@item.price</td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.RideID }) |
                @Html.ActionLink("Details", "Details", new { id = item.RideID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.RideID })
            </td>
        </tr>
    }
</table>

MvcRides/Views/Ride/New.cshtml
@model MvcRides.Models.Ride
@{
    ViewBag.Title = "List";
}


<div class="banner" id="ridebanner">
    <h2>List of rides</h2>
</div>

    //build my rendering loop
<div class="recadd">
    @Html.ActionLink("New Ride", "New", "Ride")
</div>

@{
    ViewBag.Title = "New";
}

<h2>New Ride</h2>



<form id="myform" action="/Ride/Create" method="POST">
    <div class="inputrow">
        <label class="inputlabel"> Departure City</label>
        <input type="text" name="departureCity" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Arrival City</label>
        <input type="text" name="arrivalCity" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Pick Spot </label>
        <input type="text" name="pickSpot" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Drop Spot </label>
        <input type="text" name="dropSpot" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Distance </label>
        <input type="text" name="distance" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Departure Date </label>
        <input type="text" name="departureDate" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Departure Time </label>
        <input type="text" name="departureTime" />
    </div>
    <div class="inputrow">
        <label class="inputlabel"> Price </label>
        <input type="text" name="price" />
    </div>

    <div class="inputrow">
        <input type="submit" value="add ride" />
    </div>
</form>
<br />

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}